### ISSUE TITLE
`mitmdump -s addons.py` 命令报错

### ISSUE THREAD

**Issue by xingfanxia** [747929791/majsoul_wrapper#15]
这个命令报错..
```
╰─❯ mitmdump -s addons.py

Traceback (most recent call last):
  File "/opt/homebrew/bin/mitmdump", line 8, in <module>
    sys.exit(mitmdump())
  File "/opt/homebrew/lib/python3.9/site-packages/mitmproxy/tools/_main.py", line 164, in mitmdump
    m = run(dump.DumpMaster, cmdline.mitmdump, args, extra)
  File "/opt/homebrew/lib/python3.9/site-packages/mitmproxy/tools/_main.py", line 71, in run
    opts = options.Options()
  File "/opt/homebrew/lib/python3.9/site-packages/mitmproxy/options.py", line 50, in __init__
    self.add_option(
  File "/opt/homebrew/lib/python3.9/site-packages/mitmproxy/optmanager.py", line 109, in add_option
    self._options[name] = _Option(name, typespec, default, help, choices)
  File "/opt/homebrew/lib/python3.9/site-packages/mitmproxy/optmanager.py", line 34, in __init__
    typecheck.check_option_type(name, default, typespec)
  File "/opt/homebrew/lib/python3.9/site-packages/mitmproxy/utils/typecheck.py", line 73, in check_option_type
    elif not isinstance(value, typeinfo):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 720, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 723, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks```

**Comment by xingfanxia** [comment]
好像需要3.7以下的py版本?
