### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by ghost** [747929791/majsoul_wrapper#26]
参考了其他issues, 使用了3.7的python和5.0.0的mitmproxy
> pip show mitmproxy
Name: mitmproxy
Version: 5.0.0
Summary: An interactive, SSL/TLS-capable intercepting proxy for HTTP/1, HTTP/2, and WebSockets.
Home-page: http://mitmproxy.org
Author: Aldo Cortesi
Author-email: aldo@corte.si
License: MIT
Location: c:\users\cczhao\appdata\local\programs\python\python37\lib\site-packages
Requires: pyOpenSSL, hyperframe, h2, protobuf, ruamel.yaml, passlib, ldap3, urwid, blinker, publicsuffix2, pyasn1, click, wsproto, flask, sortedcontainers, tornado, kaitaistruct, pyperclip, certifi, cryptography, pydivert, Brotli, zstandard, pyparsing
Required-by:
> python --version
Python 3.7.9

运行mitmdump -s addons.py时报错
Traceback (most recent call last):
  File "c:\users\cczhao\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\cczhao\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cczhao\AppData\Local\Programs\Python\Python37\Scripts\mitmdump.exe\__main__.py", line 7, in <module>
  File "c:\users\cczhao\appdata\local\programs\python\python37\lib\site-packages\mitmproxy\tools\_main.py", line 152, in mitmdump
    from mitmproxy.tools import dump
  File "c:\users\cczhao\appdata\local\programs\python\python37\lib\site-packages\mitmproxy\tools\dump.py", line 1, in <module>
    from mitmproxy import addons
  File "c:\users\cczhao\appdata\local\programs\python\python37\lib\site-packages\mitmproxy\addons\__init__.py", line 12, in <module>
    from mitmproxy.addons import onboarding
  File "c:\users\cczhao\appdata\local\programs\python\python37\lib\site-packages\mitmproxy\addons\onboarding.py", line 2, in <module>
    from mitmproxy.addons.onboardingapp import app
  File "c:\users\cczhao\appdata\local\programs\python\python37\lib\site-packages\mitmproxy\addons\onboardingapp\__init__.py", line 3, in <module>
    from flask import Flask, render_template
  File "c:\users\cczhao\appdata\local\programs\python\python37\lib\site-packages\flask\__init__.py", line 14, in <module>
    from jinja2 import escape
  File "c:\users\cczhao\appdata\local\programs\python\python37\lib\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "c:\users\cczhao\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "c:\users\cczhao\appdata\local\programs\python\python37\lib\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "c:\users\cczhao\appdata\local\programs\python\python37\lib\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (c:\users\cczhao\appdata\local\programs\python\python37\lib\site-packages\markupsafe\__init__.py)

**Comment by dapiao-zhangwan** [comment]
https://blog.csdn.net/wm9028/article/details/124455181
我看了这个好了
pip install markupsafe==2.0.1
