### ISSUE TITLE
pbjs把json转为proto的过程报错

### ISSUE THREAD

**Issue by Tongs2000** [747929791/majsoul_wrapper#29]
% pbjs -t  proto3 liqi.json > liqi.proto
/usr/local/lib/node_modules/pbjs/node_modules/protocol-buffers-schema/parse.js:600
        throw new Error('Unexpected token: ' + tokens[0])
        ^

Error: Unexpected token: {
    at Function.parse (/usr/local/lib/node_modules/pbjs/node_modules/protocol-buffers-schema/parse.js:600:15)
    at exports.parseSchema (/usr/local/lib/node_modules/pbjs/index.js:6:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/pbjs/cli.js:21:20)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.17.0

不知如何解决

**Comment by Fistre** [comment]
把pbjs和protobufjs都卸了然后npm install -g protobufjs-cli
