### ISSUE TITLE
版本有更新 游戏开始的WS好像有更新，目前无法使用了

### ISSUE THREAD

**Issue by moyuqianshi** [747929791/majsoul_wrapper#3]
可以更新一下吗   🙇

**Comment by moyuqianshi** [comment]
Traceback (most recent call last):
  File "main.py", line 742, in <module>
    MainLoop(level=level)
  File "main.py", line 705, in MainLoop
    while not aiWrapper.isPlaying():
  File "main.py", line 107, in isPlaying
    result = liqiProto.parse(flow_msg)
  File "C:\xxxx\MajsoulAI-master\majsoul_wrapper\liqi.py", line 84, in parse
    proto_domain = self.jsonProto['nested'][lq]['nested'][service]['methods'][rpc]
KeyError: 'fetchABMatchInfo'
